services:
  app:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8088:8088"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8088
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION_NAME=definitions
      - API_ACESS_TOKEN=${GIGACHAT_AUTH_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - qdrant
    networks:
      - app_network

  qdrant:
    image: qdrant/qdrant:v1.16
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    env_file:
      - .env
    networks:
      - app_network


  loader:
    build:
      context: src
      dockerfile: Dockerfile
    command: ["python", "/app/tools/fill_qdrant.py"]
    environment:
      - PYTHONPATH=/app
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION_NAME=definitions
      - API_ACESS_TOKEN=${GIGACHAT_AUTH_KEY}
    volumes:
        - ./data:/app/data
    depends_on:
      - qdrant
    env_file:
      - .env
    networks:
      - app_network

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI (консоль)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    networks:
      - app_network

  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/mlflow-artifacts --ignore-existing;
      echo 'Bucket mlflow-artifacts created successfully';
      "
    networks:
      - app_network

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    command: >
      sh -c "mlflow server --host 0.0.0.0 --port 5000 --default-artifact-root s3://mlflow-artifacts/"
    depends_on:
      - minio
      - minio-init
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  qdrant_storage:
  minio_data: